### ISSUE TITLE
Logical sorting

### ISSUE THREAD

**Issue by Developer-Mike** [antoKeinanen/obsidian-advanced-merger#10]
**Describe the solution you'd like**
If you have your files named like `1.1 Title` ... `20.1 Title`, it does not sort them correctly.

**Describe the solution you've considered**
You can use a collator for correct sorting.
```ts
var collator = new Intl.Collator(undefined, { numeric: true });
collator.compare(filename1, filename2);
```

**Comment by antoKeinanen** [comment]
Hi and sorry for the wait. I have now added the requested features. You should be able to change the sort method in the plugin settings.
