### ISSUE TITLE
exclude properties of merged notes during merge

### ISSUE THREAD

**Issue by osaze-nosaze** [antoKeinanen/obsidian-advanced-merger#11]
**Is your feature request related to a problem? Please describe.**
The yaml/properties of merged notes are included in merges. This makes it difficult to produce clean documents for distribution to colleagues or long manuscripts to publishers, unless one manually deletes the yaml/properties.

**Describe the solution you'd like**
I want to be able to merge the notes in a folder without their yaml/properties included in the resulting merged note.

**Describe alternatives you've considered**
You might include a toggle button in the plugin's options page that allows the user to select whether or not they want to include note yaml/properties in the merge always. You might also place that toggle in a dialogue box (I beg your pardon if that is the wrong term) that pops up whenever the user clicks the "merge folder" command, so that they can make that choice for each merge instance.

**Additional context**
This feature would facilitate the merging of atomic notes into longform documents for distribution, the receiver of which usually does not require to see the yaml/properties of the component notes.

**Comment by antoKeinanen** [comment]
Thank you for your feature request! I will look into this and see what I can do.

**Comment by osaze-nosaze** [comment]
Thank you for your prompt response. Is it possible, while you are on this matter, to look at excluding the filename also from the merged document. This is for the same reason as that for removing the yaml/properties.

**Comment by osaze-nosaze** [comment]
I seem to have closed this issue mistakenly. I am sorry.

**Comment by antoKeinanen** [comment]
Hi! Sorry, but I don't think this is possible.
