### ISSUE TITLE
"Failed to install plugin Advanced Merger."

### ISSUE THREAD

**Issue by sdnnvs** [antoKeinanen/obsidian-advanced-merger#9]
**Describe the bug**
The plugin doesn't install.

**To Reproduce**
1. Go to 'Community Plugins'
2. Click on 'Install Advanced Merger'
3. See error

**Expected behavior**
Error in plugin installation.

**Screenshots**
<img width="227" alt="image" src="https://github.com/antoKeinanen/obsidian-advanced-merger/assets/55322151/3696c42d-4cdc-430c-979a-05d71240c6f7">

**System information:**
 - OS: Windows 11
 - Obsidian version 1.2.8
 - Plugin version 1.4

**Additional context**
Strange plugin versions: 1.3.0 in GitHub, 1.4.0 in Obsidian's Community Plugin

**Comment by antoKeinanen** [comment]
Hello and thank you for the bug report. Can you please provide more information?
- Do you still have this issue?
- Please provide the link for the `Strange plugin`
